name: CI/CD

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run container
        run: |
          sudo docker network create my-network
          sudo docker build -t mongo_image roles/db/files                                                                                                                                                         
          sudo docker run -d --name mongo_server --network my-network mongo_image
          sudo docker build -t api_image roles/api/files   
          sudo docker run -d --name flask --network my-network api_image
          sudo docker build -t web_image roles/web/files 
          docker run -d -p 80:80 --name web_server --network my-network web_image
      
      - name: Test api
        run:  python3 test_api.py

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Docker Image Mongodb
        uses: docker/build-push-action@v2
        with:  
          context: roles/db/files
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my_service:${{ github.ref }}
      
      - name: Build and Push Docker Image web
        uses: docker/build-push-action@v2
        with:  
          context: roles/web/files
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my_service:${{ github.ref }}
      
      - name: Build and Push Docker Image api
        uses: docker/build-push-action@v2
        with:  
          context: roles/api/files
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my_service:${{ github.ref }}
      
