name: CI/CD

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run container
        run: |
          sudo docker compose build
          sudo docker compose up
      
      - name: check container
        run: sudo docker ps 


      - name: Test api
        run:  python test_api.py

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Docker Image Mongodb
        uses: docker/build-push-action@v2
        with:  
          context: roles/db/files
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my_service:${{ github.ref }}
      
      - name: Build and Push Docker Image web
        uses: docker/build-push-action@v2
        with:  
          context: roles/web/files
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my_service:${{ github.ref }}
      
      - name: Build and Push Docker Image api
        uses: docker/build-push-action@v2
        with:  
          context: roles/api/files
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my_service:${{ github.ref }}
      
